"""
Reflection model — a cross-episode behavioral pattern or timeless insight.

Reflections are generated by Batch 2 when 3 or more distinct episodes
across 2 or more different days support a consistent pattern. They encode
what the coach has learned about this specific user's tendencies,
preferences, and risks.
"""

from __future__ import annotations

from datetime import date, datetime
from typing import Literal

from pydantic import BaseModel, Field


class Reflection(BaseModel):
    """
    A behavioral pattern or coaching insight derived from multiple episodes.

    Confidence degrades over time if no new supporting episodes are found.
    When supporting episodes are superseded, the reflection is flagged for
    re-evaluation and may be downgraded or deactivated by Batch 2.
    """

    id: str
    user_id: str
    pattern_type: Literal[
        "adherence", "recovery", "motivation", "risk", "progress", "coaching_style"
    ]
    observation: str
    coach_action: str
    supporting_episode_ids: list[str]
    supporting_episode_summaries: list[str] = Field(default_factory=list)
    confidence: Literal["low", "medium", "high"]
    first_observed: date
    last_confirmed: date
    episode_count: int
    active: bool = True
    needs_reeval: bool = False
    created_at: datetime = Field(default_factory=datetime.utcnow)
